### ISSUE TITLE
Steam has no response after logging in

### ISSUE THREAD

**Issue by CHARLESxyz** [CSGOAced/CSGOAced.xyz#2]
Steam does not have any response after logging in, should i check where?

**Comment by ItsCEED** [comment]
This project is pretty much dead. So dont expect a respons or help.

**Comment by TiagoSeverino** [comment]
Can you explain a little more detailed?

**Comment by CHARLESxyz** [comment]
After I log in using the steam account, the site does not have any response to just jump to the home page of the site.

**Comment by TiagoSeverino** [comment]
I guess you don't own csgo or have private profile, can you send me your profile?

**Comment by CHARLESxyz** [comment]
my profile: http://steamcommunity.com/id/hidzamaru_sidzui/

**Comment by TiagoSeverino** [comment]
@CHARLESxyz Was your profile private? You are registered in csgo aced.
