### ISSUE TITLE
Chat and deposit not work

### ISSUE THREAD

**Issue by hakersky** [CSGOAced/CSGOAced.xyz#3]
Hi,
I have several problems with the site.
- Chat isn't working
- Deposit site can't reach steam inventory.
Can you help me?

**Comment by TiagoSeverino** [comment]
Sure, can you give me more details?

**Comment by hakersky** [comment]
I want to start demo site on localhost server. I can only login, but nothing more works. In developer console in browser I can see that it is looking for `http://localhost/socket.io/?EIO=3&transport=polling&t=M0y0P3G`.

**Comment by TiagoSeverino** [comment]
Have you installed [Node Server](https://github.com/CSGOAced/CSGOAced.xyz-NodeServer) ?

**Comment by hakersky** [comment]
I installed, but I don't know if I did it good :/

**Comment by TiagoSeverino** [comment]
Change [Node Path](https://github.com/CSGOAced/CSGOAced.xyz/blob/master/lib/controller/Config.php.default#L20) to http://localhost:3000

**Comment by hakersky** [comment]
Oh... Thanks, but deposit site still not working, no one of my skins appears on it.

**Comment by TiagoSeverino** [comment]
Do you have any registry in the database for the Skins table?
Try to change the time where the node server [updates/loads](https://github.com/CSGOAced/CSGOAced.xyz-NodeServer/blob/master/config.json.default#L16) the skins to database. It is set by default to 5:30AM of everyday.

**Comment by hakersky** [comment]
OK, but there is next problem -_-
```
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds
ur MySQL server version for the right syntax to use near 'IF NOT EXISTS(SELECT MarketName FROM
 WHERE MarketName = 'MP9 | Sand Dashed' at line 1
```

**Comment by TiagoSeverino** [comment]
You need to install mariaDB

**Comment by hakersky** [comment]
And next
```
         index.js:55
                for (row = results.length - 1; row >= 0; row--) {
                                   ^
TypeError: Cannot read property 'length' of undefined
```

**Comment by TiagoSeverino** [comment]
Do you have mariaDB installed?

**Comment by hakersky** [comment]
Yes, I am using WampServer and MariaDB is installed.

**Comment by TiagoSeverino** [comment]
It's a bug, I'm gonna fix it, wait a sec.
Results is undefined because you don't have 8 chat msg in server yet, I'm gonna add a confirmation before, thank you!

**Comment by TiagoSeverino** [comment]
Update node server repo and relaunch it. It should be fine, but I haven't tested

**Comment by hakersky** [comment]
I have one more question, I have to use MariaDB, I should import database files to MySQL or to MariaDB database?

**Comment by TiagoSeverino** [comment]
MariaDB, if you want to use MySQL you need to change some queries.
Did the last update fixed the issue?

**Comment by hakersky** [comment]
I want to try, but if I switched off Mysql, node server can't connect to MariaDB, bacause there is no new info in nodelog table.

**Comment by hakersky** [comment]
Skins prices are also not updated

**Comment by TiagoSeverino** [comment]
You don't need MySQL, CSGOAced only uses MariaDB, just put your MariaDB server credentials in config files and install the database in MariaDB server

**Comment by hakersky** [comment]
Thanks for help :)

**Comment by TiagoSeverino** [comment]
No problem!
