### ISSUE TITLE
Refreshing offers does not work

### ISSUE THREAD

**Issue by hakersky** [CSGOAced/CSGOAced.xyz#4]
Problem with changing the status of the exchange offer. After sending the offer and accepting the exchange offer, the status does not change, status remains: Active or Created Needs Confirmatio.

**Comment by TiagoSeverino** [comment]
I think it has something to do with [steam-tradeoffer-manager](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager). Maybe the code is outdated
